### ISSUE TITLE
iPad Pro icon missing

### ISSUE THREAD

**Issue by mydea** [isleofcode/splicon#14]
Hi,

not 100% sure, but I think the iPad Pro icon is missing.

According to here:
https://cordova.apache.org/docs/en/latest/config_ref/images.html

The iPad Pro uses:

`<icon src="res/ios/icon-83.5@2x.png" width="167" height="167" />`

**Comment by jordanyee** [comment]
@mydea Good catch, it's definitely missing. I've got some time in an airport this weekend so I'll work on it there!
